# Generated by Django 5.2.5 on 2025-08-20 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='slug',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Доменное имя'),
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Название модели')),
                ('slug', models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='Доменное имя')),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carbrand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
                'db_table': 'Модель',
            },
        ),
    ]
