# Generated by Django 5.2.5 on 2025-08-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_alter_carbrand_slug_carmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Цена')),
                ('mileage', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Пробег')),
                ('date_of_producing', models.DateTimeField(verbose_name='Дата выпуска')),
                ('is_broken', models.BooleanField(default=False, verbose_name='Попадание в ДТП')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carbrand', verbose_name='Марка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carmodel', verbose_name='Модель')),
            ],
            options={
                'verbose_name': 'Автомобиль',
                'verbose_name_plural': 'Автомобили',
                'db_table': 'Автомобиль',
            },
        ),
    ]
