# Generated by Django 5.2.5 on 2025-08-20 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_car'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='Car',
        ),
        migrations.AlterModelTable(
            name='carbrand',
            table='CarBrand',
        ),
        migrations.AlterModelTable(
            name='carmodel',
            table='CarModel',
        ),
    ]
