# Generated by Django 5.2.5 on 2025-08-20 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_alter_car_table_alter_carbrand_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='date_of_producing',
            field=models.DateField(verbose_name='Дата выпуска'),
        ),
    ]
