# Generated by Django 5.2.5 on 2025-08-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_alter_car_date_of_producing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='date_of_producing',
        ),
        migrations.AddField(
            model_name='car',
            name='country',
            field=models.CharField(blank=True, null=True, verbose_name='Страна производства'),
        ),
        migrations.AddField(
            model_name='car',
            name='date_of_technical_maintenance',
            field=models.DateField(blank=True, null=True, verbose_name='Дата последнего ТО'),
        ),
        migrations.AddField(
            model_name='car',
            name='year_produced',
            field=models.IntegerField(blank=True, null=True, verbose_name='Дата производства'),
        ),
    ]
