# Generated by Django 5.2.5 on 2025-08-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_remove_car_date_of_producing_car_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
        migrations.DeleteModel(
            name='CarModel',
        ),
    ]
