# Generated by Django 5.2.5 on 2025-08-20 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_alter_car_model_delete_carmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='carbrand',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='Доменное имя'),
        ),
    ]
