# Generated by Django 5.2.5 on 2025-08-21 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_car_image_alter_carbrand_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Доменное имя')),
            ],
            options={
                'verbose_name': 'Категория автомобилей',
                'verbose_name_plural': 'Категории автомобилей',
                'db_table': 'СarCategory',
            },
        ),
        migrations.CreateModel(
            name='CarTuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Доменное имя')),
            ],
            options={
                'verbose_name': 'Вид топлива',
                'verbose_name_plural': 'Виды топлива',
                'db_table': 'СarTuel',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='engine_displacement',
            field=models.IntegerField(blank=True, null=True, verbose_name='Объем двигателя'),
        ),
        migrations.AddField(
            model_name='carbrand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_brand_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carbrand', verbose_name='Марка'),
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='car',
            name='car_tuel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.cartuel', verbose_name='Топливо'),
        ),
    ]
