# Generated by Django 5.2.5 on 2025-08-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_carcategory_cartuel_car_engine_displacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carcategory',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='carcategory',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Доменное имя'),
        ),
        migrations.AlterField(
            model_name='cartuel',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cartuel',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Доменное имя'),
        ),
    ]
