# Generated by Django 5.2.5 on 2025-08-21 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_alter_carcategory_name_alter_carcategory_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_tuel',
        ),
        migrations.RemoveField(
            model_name='car',
            name='category',
        ),
        migrations.CreateModel(
            name='ElectricCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('price', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Цена')),
                ('mileage', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Пробег')),
                ('year_produced', models.IntegerField(blank=True, null=True, verbose_name='Дата производства')),
                ('date_of_technical_maintenance', models.DateField(blank=True, null=True, verbose_name='Дата последнего ТО')),
                ('is_broken', models.BooleanField(default=False, verbose_name='Попадание в ДТП')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('country', models.CharField(blank=True, null=True, verbose_name='Страна производства')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images', verbose_name='Изображение')),
                ('battery_capacity', models.IntegerField(verbose_name='Емкость батареи (кВт⋅ч)')),
                ('range', models.IntegerField(verbose_name='Запас хода (км)')),
                ('charging_time', models.FloatField(verbose_name='Время полной зарядки (ч)')),
                ('motor_power', models.IntegerField(verbose_name='Мощность двигателя (кВт)')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carbrand', verbose_name='Марка')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Электромобиль',
                'verbose_name_plural': 'Электромобили',
            },
        ),
        migrations.CreateModel(
            name='FuelCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('price', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Цена')),
                ('mileage', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Пробег')),
                ('year_produced', models.IntegerField(blank=True, null=True, verbose_name='Дата производства')),
                ('date_of_technical_maintenance', models.DateField(blank=True, null=True, verbose_name='Дата последнего ТО')),
                ('is_broken', models.BooleanField(default=False, verbose_name='Попадание в ДТП')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('country', models.CharField(blank=True, null=True, verbose_name='Страна производства')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images', verbose_name='Изображение')),
                ('fuel_type', models.CharField(choices=[('gasoline', 'Бензин'), ('diesel', 'Дизель'), ('gas', 'Газ')], max_length=20, verbose_name='Тип топлива')),
                ('engine_displacement', models.IntegerField(blank=True, null=True, verbose_name='Объем двигателя')),
                ('fuel_consumption', models.FloatField(verbose_name='Расход топлива (л/100км)')),
                ('fuel_tank_capacity', models.IntegerField(verbose_name='Объем топливного бака (л)')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carbrand', verbose_name='Марка')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Автомобиль на топливе',
                'verbose_name_plural': 'Автомобили на топливе',
            },
        ),
        migrations.DeleteModel(
            name='CarTuel',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
    ]
