# Generated by Django 5.2.5 on 2025-08-21 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_remove_car_brand_remove_car_car_tuel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electriccar',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='Доменное имя'),
        ),
        migrations.AddField(
            model_name='fuelcar',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, unique=True, verbose_name='Доменное имя'),
        ),
    ]
