# Generated by Django 5.2.5 on 2025-08-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_electriccar_slug_fuelcar_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='electriccar',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания объявления'),
        ),
        migrations.AddField(
            model_name='fuelcar',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата создания объявления'),
        ),
    ]
