# Generated by Django 5.2.5 on 2025-08-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0013_electriccar_date_created_fuelcar_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electriccar',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата создания объявления'),
        ),
        migrations.AlterField(
            model_name='fuelcar',
            name='date_created',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Дата создания объявления'),
        ),
    ]
