# Generated by Django 5.2.5 on 2025-08-21 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_alter_electriccar_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electriccar',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='fuelcar',
            name='date_created',
        ),
    ]
