# Generated by Django 5.2.5 on 2025-08-21 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0017_remove_electriccar_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelcar',
            name='transmission',
            field=models.CharField(choices=[('mechanical', 'Механическая'), ('automatic', 'Автоматическая'), ('robotic', 'Робот')], default=('mechanical', 'Механическая'), max_length=20, verbose_name='Тип коробки передач'),
        ),
    ]
