# Generated by Django 5.2.5 on 2025-08-21 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0018_fuelcar_transmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electriccar',
            name='image',
        ),
        migrations.RemoveField(
            model_name='fuelcar',
            name='image',
        ),
        migrations.CreateModel(
            name='ElectricCarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car.electriccar', verbose_name='Электромобиль')),
            ],
            options={
                'verbose_name': 'Фото электромобиля',
                'verbose_name_plural': 'Фото электромобилей',
            },
        ),
        migrations.CreateModel(
            name='FuelCarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/')),
                ('is_main', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car.fuelcar', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'Фото автомобиля на топливе',
                'verbose_name_plural': 'Фото автомобилей на топливе',
            },
        ),
    ]
