# Generated by Django 5.2.5 on 2025-08-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0019_remove_electriccar_image_remove_fuelcar_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electriccar',
            name='is_main_car',
            field=models.BooleanField(default=False, verbose_name='Самый актуальный автомобиль'),
        ),
        migrations.AddField(
            model_name='fuelcar',
            name='is_main_car',
            field=models.BooleanField(default=False, verbose_name='Самый актуальный автомобиль'),
        ),
    ]
