# Generated by Django 5.2.5 on 2025-08-22 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0020_electriccar_is_main_car_fuelcar_is_main_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electriccar',
            name='is_main_car',
        ),
        migrations.RemoveField(
            model_name='fuelcar',
            name='is_main_car',
        ),
    ]
